name: aasan
description: Aassan
version: 1.0.0
homepage: https://www.aasan.com

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  email_validator: ^2.0.1
#  date_format: ^2.0.2

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
